borders: null
computer:
  machine: x86_64
  node: alberts-air.crulrg.local
  processor: i386
  release: 20.3.0
  system: Darwin
  version: 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64'
default_values_dict:
  background: 499999.99999999994
  bleach: true
  darkcount: 0
  dwelltime: 1.0e-05
  im_size_nm: 1000
  molecules_disposition: null
  nb_molecules_per_point_src: 30
  nb_pt_src: 8
  noise: true
  p_ex: 0.001
  p_sted: 3.0e-06
  pixelsize: 2.0e-08
n_divs_default: 25
nbre_trials: 1
obj_names:
- Resolution
- Bleach
- SNR
optim_length: 40
param_names:
- p_sted
- p_ex
params_conf:
  p_ex: 2.0e-05
  p_sted: 0
regressor_args:
  Bleach:
    alpha_2: 4.5
    alpha_init: 277.77777777777777
    lambda_init: 0.25
  Resolution:
    alpha_2: 45000.0
    alpha_init: 0.1111111111111111
    lambda_init: 2.5e-05
  SNR:
    alpha_2: 1250.0
    alpha_init: 4.0
    lambda_init: 0.0011111111111111111
  default:
    alpha_1: 5000.0
    alpha_2: 49.94414719461602
    alpha_init: 100.11183053174646
    compute_score: true
    degree: 2
    fit_intercept: true
    lambda_1: 1.0e-06
    lambda_2: 1.0e-06
    lambda_init: 1.4595412992911199
    tol: 1.0e-06
regressor_name: sklearn_BayesRidge
save_folder: debug_trialX
with_time: true
x_maxs:
- 0.0416
- 0.0064
x_mins:
- 0
- 6.25e-06
